### ISSUE TITLE
enqueue_style & enqueue_script with & without Webpack

### ISSUE THREAD

**Issue by yuriipavlov** [SolidBunch/starter-kit#5]
![16-01-2019-10-32-13](https://user-images.githubusercontent.com/25429417/51276976-ecee8700-19de-11e9-8419-2c5d944e00d8.png)
need to bring to one standard and take into account that the Theme can be used without webpack

**Comment by zyv4yk** [comment]
[https://github.com/SolidBunch/starter-kit/pull/9](PR#9)
